### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by SAUCYSOUP76** [StevenTso/ACS-ACR122U-NFC-Reader#7]
Traceback (most recent call last):
  File "NFCReader.py", line 13, in <module>
    r = readers()
  File "/usr/lib/python2.7/dist-packages/smartcard/System.py", line 42, in readers
    return smartcard.reader.ReaderFactory.ReaderFactory.readers(groups)
  File "/usr/lib/python2.7/dist-packages/smartcard/reader/ReaderFactory.py", line 58, in readers
    zreaders += fm(groups)
  File "/usr/lib/python2.7/dist-packages/smartcard/pcsc/PCSCReader.py", line 108, in readers
    hcontext = PCSCContext().getContext()
  File "/usr/lib/python2.7/dist-packages/smartcard/pcsc/PCSCContext.py", line 53, in __init__
    PCSCContext.instance = PCSCContext.__PCSCContextSingleton()
  File "/usr/lib/python2.7/dist-packages/smartcard/pcsc/PCSCContext.py", line 40, in __init__
    raise EstablishContextException(hresult)
smartcard.pcsc.PCSCExceptions.EstablishContextException: 'Failure to establish context: Service not available.'

**Comment by ApplicationDeveloper** [comment]
> Traceback (most recent call last):
> File "NFCReader.py", line 13, in 
> r = readers()
> File "/usr/lib/python2.7/dist-packages/smartcard/System.py", line 42, in readers
> return smartcard.reader.ReaderFactory.ReaderFactory.readers(groups)
> File "/usr/lib/python2.7/dist-packages/smartcard/reader/ReaderFactory.py", line 58, in readers
> zreaders += fm(groups)
> File "/usr/lib/python2.7/dist-packages/smartcard/pcsc/PCSCReader.py", line 108, in readers
> hcontext = PCSCContext().getContext()
> File "/usr/lib/python2.7/dist-packages/smartcard/pcsc/PCSCContext.py", line 53, in **init**
> PCSCContext.instance = PCSCContext.__PCSCContextSingleton()
> File "/usr/lib/python2.7/dist-packages/smartcard/pcsc/PCSCContext.py", line 40, in **init**
> raise EstablishContextException(hresult)
> smartcard.pcsc.PCSCExceptions.EstablishContextException: 'Failure to establish context: Service not available.'

try:
sudo apt install pcscd
